### ISSUE TITLE
哈喽 老哥 来问个问题

### ISSUE THREAD

**Issue by jaceyi** [ocian/shu.moe#1]
https://github.com/bripkens/connect-history-api-fallback/issues/80
你提的这个 issue 有解决办法了么？

**Comment by jaceyi** [comment]
这个库看起来几年没更新了，应该是 webpack 的问题吧

**Comment by ocian** [comment]
那个项目下贴的，就是我的解决办法，我只能说能用
在开发的时候，所有资源文件都放根目录，然后根据资源文件后缀名去匹配
效果就是，`/a/b/c.(js|css|svg|png)$` 这类文件，替换成 `/c.(js|css|svg|png)$` 这种样子

看起来是 webpack 换组件了，之前一直没这种问题

**Comment by ocian** [comment]
@jaceyi

**Comment by ocian** [comment]
publicPath 也可以试试
